### ISSUE TITLE
add option to test for response sets?

### ISSUE THREAD

**Issue by maxAgostini** [JannisCodes/PsyCorona-WebApp#12]
it should be possible to do this with only the means and sds per country

**Comment by JannisCodes** [comment]
Example Mockup

<img width="1087" alt="Screenshot 2020-07-16 at 16 40 27" src="https://user-images.githubusercontent.com/38377896/89872892-e5429480-dbb9-11ea-9f1a-d571de84ec28.png">

**Comment by JannisCodes** [comment]
implemented in version late Oct. 2020
