### ISSUE TITLE
Bubble Chart y-axis not correct for Hope Variable

### ISSUE THREAD

**Issue by maxAgostini** [JannisCodes/PsyCorona-WebApp#19]
![image](https://user-images.githubusercontent.com/62992351/90248627-5b086380-de39-11ea-991f-99b6b81d3c46.png)

**Comment by JannisCodes** [comment]
problem with factor to numeric transformation. Solved with deployment and [commit 887d12b](https://github.com/JannisCodes/PsyCorona-WebApp/commit/887d12babbff3b7a82228cc304c0d2fed7826306?branch=887d12babbff3b7a82228cc304c0d2fed7826306&diff=unified)
